[I 18:30:03.299 LabApp] Copying /home/ubuntu/.ipython/profile_default/ipython_nbconvert_config.py -> /home/ubuntu/.jupyter/jupyter_nbconvert_config.py
[W 18:30:03.303 LabApp] Config option `base_kernel_url` not recognized by `LabApp`.  Did you mean one of: `base_project_url, base_url`?
[I 18:30:03.311 LabApp] Writing notebook server cookie secret to /home/ubuntu/.local/share/jupyter/runtime/notebook_cookie_secret
[W 18:30:03.535 LabApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 18:30:03.548 LabApp] Loading IPython parallel extension
[I 18:30:04.000 LabApp] JupyterLab extension loaded from /usr/local/anaconda/lib/python3.6/site-packages/jupyterlab
[I 18:30:04.000 LabApp] JupyterLab application directory is /usr/local/anaconda/share/jupyter/lab
[I 18:30:04.003 LabApp] Serving notebooks from local directory: /
[I 18:30:04.003 LabApp] The Jupyter Notebook is running at:
[I 18:30:04.003 LabApp] http://run-5e8780890d6ef6000613fbdc-7p8nf:8888/joshpoduska/infectious-disease-data/notebookSession/5e8780890d6ef6000613fbdc/
[I 18:30:04.003 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 18:30:05.586 LabApp] 302 GET /joshpoduska/infectious-disease-data/notebookSession/5e8780890d6ef6000613fbdc/ (100.96.170.253) 0.57ms
[I 18:30:08.572 LabApp] 302 GET /joshpoduska/infectious-disease-data/notebookSession/5e8780890d6ef6000613fbdc/ (100.96.170.253) 0.55ms
[I 18:30:08.718 LabApp] 302 GET /joshpoduska/infectious-disease-data/notebookSession/5e8780890d6ef6000613fbdc/ (100.96.170.253) 0.49ms
[W 18:30:12.887 LabApp] 404 GET /joshpoduska/infectious-disease-data/notebookSession/5e8780890d6ef6000613fbdc/lab/api/workspaces/joshpoduska/infectious-disease-data/notebookSession/5e8780890d6ef6000613fbdc/lab?1585938612365 (100.96.170.253): Workspace 'joshpoduska/infectious-disease-data/notebookSession/5e8780890d6ef6000613fbdc/lab' ('joshpoduskainfectious-disease-datanotebooksession5e8780890d6ef6000613fbdclab-9b2f') not found
[W 18:30:12.887 LabApp] Workspace 'joshpoduska/infectious-disease-data/notebookSession/5e8780890d6ef6000613fbdc/lab' ('joshpoduskainfectious-disease-datanotebooksession5e8780890d6ef6000613fbdclab-9b2f') not found
[W 18:30:12.887 LabApp] 404 GET /joshpoduska/infectious-disease-data/notebookSession/5e8780890d6ef6000613fbdc/lab/api/workspaces/joshpoduska/infectious-disease-data/notebookSession/5e8780890d6ef6000613fbdc/lab?1585938612365 (100.96.170.253) 205.57ms referer=https://try.dominodatalab.com/joshpoduska/infectious-disease-data/notebookSession/5e8780890d6ef6000613fbdc/lab/tree/mnt?
[I 18:30:12.943 LabApp] Node v8.10.0
    
[I 18:30:12.948 LabApp] Build is up to date
[I 18:32:09.083 LabApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
