[I 14:50:45.770 LabApp] Copying /home/ubuntu/.ipython/profile_default/ipython_nbconvert_config.py -> /home/ubuntu/.jupyter/jupyter_nbconvert_config.py
[W 14:50:45.774 LabApp] Config option `base_kernel_url` not recognized by `LabApp`.  Did you mean one of: `base_project_url, base_url`?
[I 14:50:45.784 LabApp] Writing notebook server cookie secret to /home/ubuntu/.local/share/jupyter/runtime/notebook_cookie_secret
[W 14:50:46.004 LabApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 14:50:46.017 LabApp] Loading IPython parallel extension
[I 14:50:46.499 LabApp] JupyterLab extension loaded from /usr/local/anaconda/lib/python3.6/site-packages/jupyterlab
[I 14:50:46.499 LabApp] JupyterLab application directory is /usr/local/anaconda/share/jupyter/lab
[I 14:50:46.502 LabApp] Serving notebooks from local directory: /
[I 14:50:46.502 LabApp] The Jupyter Notebook is running at:
[I 14:50:46.502 LabApp] http://run-5e947c057dcf670006b6753c-x5dl4:8888/joshpoduska/infectious-disease-data/notebookSession/5e947c057dcf670006b6753c/
[I 14:50:46.502 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 14:50:48.374 LabApp] 302 GET /joshpoduska/infectious-disease-data/notebookSession/5e947c057dcf670006b6753c/ (100.96.170.81) 0.61ms
[I 14:50:50.624 LabApp] 302 GET /joshpoduska/infectious-disease-data/notebookSession/5e947c057dcf670006b6753c/ (100.96.170.81) 0.52ms
[I 14:50:50.855 LabApp] 302 GET /joshpoduska/infectious-disease-data/notebookSession/5e947c057dcf670006b6753c/ (100.96.170.81) 0.46ms
[W 14:50:53.373 LabApp] 404 GET /joshpoduska/infectious-disease-data/notebookSession/5e947c057dcf670006b6753c/lab/api/workspaces/joshpoduska/infectious-disease-data/notebookSession/5e947c057dcf670006b6753c/lab?1586789453124 (100.96.170.81): Workspace 'joshpoduska/infectious-disease-data/notebookSession/5e947c057dcf670006b6753c/lab' ('joshpoduskainfectious-disease-datanotebooksession5e947c057dcf670006b6753clab-b07d') not found
[W 14:50:53.373 LabApp] Workspace 'joshpoduska/infectious-disease-data/notebookSession/5e947c057dcf670006b6753c/lab' ('joshpoduskainfectious-disease-datanotebooksession5e947c057dcf670006b6753clab-b07d') not found
[W 14:50:53.374 LabApp] 404 GET /joshpoduska/infectious-disease-data/notebookSession/5e947c057dcf670006b6753c/lab/api/workspaces/joshpoduska/infectious-disease-data/notebookSession/5e947c057dcf670006b6753c/lab?1586789453124 (100.96.170.81) 53.98ms referer=https://try.dominodatalab.com/joshpoduska/infectious-disease-data/notebookSession/5e947c057dcf670006b6753c/lab/tree/mnt?
[I 14:50:53.603 LabApp] Node v8.10.0
    
[I 14:50:53.607 LabApp] Build is up to date
[I 14:51:11.900 LabApp] Writing notebook-signing key to /home/ubuntu/.local/share/jupyter/notebook_secret
[W 14:51:11.904 LabApp] Notebook mnt/code/data_exploration_n_viz.ipynb is not trusted
[I 14:51:15.106 LabApp] Kernel started: e28b31d6-8aac-49f9-8797-e88fac39b6df
[W 14:52:52.106 LabApp] Notebook mnt/code/covid19-JHU.ipynb is not trusted
[I 14:52:52.844 LabApp] Kernel started: bc894683-1370-4b68-8986-449f3abdffc4
[I 14:54:52.864 LabApp] Saving file at /mnt/code/covid19-JHU.ipynb
[I 14:55:15.254 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[I 14:57:16.977 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[I 14:59:17.575 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[I 15:01:18.398 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[I 15:03:19.941 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[I 15:03:34.577 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[I 15:03:37.472 LabApp] Saving file at /mnt/code/covid19-JHU.ipynb
[I 15:04:07.534 LabApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
