[I 18:51:57.612 LabApp] Copying /home/ubuntu/.ipython/profile_default/ipython_nbconvert_config.py -> /home/ubuntu/.jupyter/jupyter_nbconvert_config.py
[W 18:51:57.616 LabApp] Config option `base_kernel_url` not recognized by `LabApp`.  Did you mean one of: `base_project_url, base_url`?
[I 18:51:57.624 LabApp] Writing notebook server cookie secret to /home/ubuntu/.local/share/jupyter/runtime/notebook_cookie_secret
[W 18:51:57.849 LabApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 18:51:57.863 LabApp] Loading IPython parallel extension
[I 18:51:58.322 LabApp] JupyterLab extension loaded from /usr/local/anaconda/lib/python3.6/site-packages/jupyterlab
[I 18:51:58.322 LabApp] JupyterLab application directory is /usr/local/anaconda/share/jupyter/lab
[I 18:51:58.325 LabApp] Serving notebooks from local directory: /
[I 18:51:58.325 LabApp] The Jupyter Notebook is running at:
[I 18:51:58.325 LabApp] http://run-5e8785a9c3e1450006159b07-5cb54:8888/joshpoduska/infectious-disease-data/notebookSession/5e8785a9c3e1450006159b07/
[I 18:51:58.325 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 18:52:00.511 LabApp] 302 GET /joshpoduska/infectious-disease-data/notebookSession/5e8785a9c3e1450006159b07/ (100.96.170.254) 0.59ms
[I 18:52:03.454 LabApp] 302 GET /joshpoduska/infectious-disease-data/notebookSession/5e8785a9c3e1450006159b07/ (100.96.170.254) 0.50ms
[I 18:52:03.576 LabApp] 302 GET /joshpoduska/infectious-disease-data/notebookSession/5e8785a9c3e1450006159b07/ (100.96.170.254) 0.54ms
[I 18:52:06.854 LabApp] Node v8.10.0
    
[I 18:52:06.876 LabApp] Build is up to date
[W 18:52:06.935 LabApp] 404 GET /joshpoduska/infectious-disease-data/notebookSession/5e8785a9c3e1450006159b07/lab/api/workspaces/joshpoduska/infectious-disease-data/notebookSession/5e8785a9c3e1450006159b07/lab?1585939926899 (100.96.170.254): Workspace 'joshpoduska/infectious-disease-data/notebookSession/5e8785a9c3e1450006159b07/lab' ('joshpoduskainfectious-disease-datanotebooksession5e8785a9c3e1450006159b07lab-a926') not found
[W 18:52:06.935 LabApp] Workspace 'joshpoduska/infectious-disease-data/notebookSession/5e8785a9c3e1450006159b07/lab' ('joshpoduskainfectious-disease-datanotebooksession5e8785a9c3e1450006159b07lab-a926') not found
[W 18:52:06.936 LabApp] 404 GET /joshpoduska/infectious-disease-data/notebookSession/5e8785a9c3e1450006159b07/lab/api/workspaces/joshpoduska/infectious-disease-data/notebookSession/5e8785a9c3e1450006159b07/lab?1585939926899 (100.96.170.254) 1.40ms referer=https://try.dominodatalab.com/joshpoduska/infectious-disease-data/notebookSession/5e8785a9c3e1450006159b07/lab/tree/mnt?
[I 18:53:45.155 LabApp] Writing notebook-signing key to /home/ubuntu/.local/share/jupyter/notebook_secret
[W 18:53:45.161 LabApp] Notebook mnt/code/data_exploration_n_viz.ipynb is not trusted
[I 18:53:48.598 LabApp] Kernel started: 7f1ce3ef-a76b-46aa-84bf-604e2db69040
[I 18:54:57.879 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[W 18:54:57.881 LabApp] Notebook mnt/code/data_exploration_n_viz.ipynb is not trusted
[I 18:56:31.936 LabApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
