[I 16:35:05.864 LabApp] Copying /home/ubuntu/.ipython/profile_default/ipython_nbconvert_config.py -> /home/ubuntu/.jupyter/jupyter_nbconvert_config.py
[W 16:35:05.868 LabApp] Config option `base_kernel_url` not recognized by `LabApp`.  Did you mean one of: `base_project_url, base_url`?
[I 16:35:05.876 LabApp] Writing notebook server cookie secret to /home/ubuntu/.local/share/jupyter/runtime/notebook_cookie_secret
[W 16:35:06.095 LabApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 16:35:06.108 LabApp] Loading IPython parallel extension
[I 16:35:06.558 LabApp] JupyterLab extension loaded from /usr/local/anaconda/lib/python3.6/site-packages/jupyterlab
[I 16:35:06.558 LabApp] JupyterLab application directory is /usr/local/anaconda/share/jupyter/lab
[I 16:35:06.561 LabApp] Serving notebooks from local directory: /
[I 16:35:06.562 LabApp] The Jupyter Notebook is running at:
[I 16:35:06.562 LabApp] http://run-5e8dfd0d1c99e700065e35fa-x9525:8888/joshpoduska/infectious-disease-data/notebookSession/5e8dfd0d1c99e700065e35fa/
[I 16:35:06.562 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 16:35:08.781 LabApp] 302 GET /joshpoduska/infectious-disease-data/notebookSession/5e8dfd0d1c99e700065e35fa/ (100.96.162.72) 0.65ms
[I 16:35:10.923 LabApp] 302 GET /joshpoduska/infectious-disease-data/notebookSession/5e8dfd0d1c99e700065e35fa/ (100.96.162.72) 0.49ms
[I 16:35:11.110 LabApp] 302 GET /joshpoduska/infectious-disease-data/notebookSession/5e8dfd0d1c99e700065e35fa/ (100.96.162.72) 0.68ms
[W 16:35:15.137 LabApp] 404 GET /joshpoduska/infectious-disease-data/notebookSession/5e8dfd0d1c99e700065e35fa/lab/api/workspaces/joshpoduska/infectious-disease-data/notebookSession/5e8dfd0d1c99e700065e35fa/lab?1586363714653 (100.96.162.72): Workspace 'joshpoduska/infectious-disease-data/notebookSession/5e8dfd0d1c99e700065e35fa/lab' ('joshpoduskainfectious-disease-datanotebooksession5e8dfd0d1c99e700065e35falab-903f') not found
[W 16:35:15.138 LabApp] Workspace 'joshpoduska/infectious-disease-data/notebookSession/5e8dfd0d1c99e700065e35fa/lab' ('joshpoduskainfectious-disease-datanotebooksession5e8dfd0d1c99e700065e35falab-903f') not found
[W 16:35:15.138 LabApp] 404 GET /joshpoduska/infectious-disease-data/notebookSession/5e8dfd0d1c99e700065e35fa/lab/api/workspaces/joshpoduska/infectious-disease-data/notebookSession/5e8dfd0d1c99e700065e35fa/lab?1586363714653 (100.96.162.72) 2.43ms referer=https://try.dominodatalab.com/joshpoduska/infectious-disease-data/notebookSession/5e8dfd0d1c99e700065e35fa/lab/tree/mnt?
[I 16:35:15.254 LabApp] Node v8.10.0
    
[I 16:35:15.259 LabApp] Build is up to date
[I 16:35:22.235 LabApp] Writing notebook-signing key to /home/ubuntu/.local/share/jupyter/notebook_secret
[W 16:35:22.241 LabApp] Notebook mnt/code/data_exploration_n_viz.ipynb is not trusted
[I 16:35:25.353 LabApp] Kernel started: b74dc3a7-e972-40f6-b08d-69364f39ddcb
[I 16:37:24.537 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[I 16:39:25.234 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[I 16:41:26.536 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[I 16:43:28.435 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[I 16:45:30.257 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[I 16:47:32.877 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[I 16:49:33.550 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[I 16:51:34.993 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[I 16:53:35.536 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[I 16:55:37.456 LabApp] Saving file at /mnt/code/data_exploration_n_viz.ipynb
[I 16:56:37.022 LabApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
